all: first_exec first_exec_child1 second_exec

first_exec: first_exec.c
	gcc -o first_exec first_exec.c

first_exec_child1: first_exec_child1.c
	gcc -o first_exec_child1 first_exec_child1.c

second_exec: second_exec.c
	gcc -o second_exec second_exec.c
